export default {
    MESSAGES_LOADING_PENDING: 'MESSAGES_PENDING',
    MESSAGES_LOADING_ERROR: 'MESSAGES_ERROR',
    MESSAGES_LOADING_SUCCESS: 'MESSAGES_SUCCESS',

    CURRENT_FOLDER_CHANGE: 'CURRENT_FOLDER_CHANGE',
    LOAD_FOLDERS_LIST: 'LOAD_FOLDERS_LIST',

    MESSAGE_LOADING_PENDING: 'MESSAGE_PENDING',
    MESSAGE_LOADING_ERROR: 'MESSAGE_ERROR',
    MESSAGE_LOADING_SUCCESS: 'MESSAGE_SUCCESS',
    CURRENT_MESSAGE_CHANGE: 'CURRENT_MESSAGE_CHANGE',
}